package com.iago.springapp.domain.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name="IMAGES", schema="IAGO")
public class Images implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private long id;
	private Items items;
	private String path;
	private Character publico;

	public Images() {
	}


	public Images(long id, Items items) {
		this.id = id;
		this.items = items;
	}
	public Images(long id, Items items, String path, Character publico) {
		this.id = id;
		this.items = items;
		this.path = path;
		this.publico = publico;
	}

	@Id 

	@Column(name="ID", nullable=false, precision=22, scale=0)
	public long getId() {
		return this.id;
	}

	public void setId(long i) {
		this.id = i;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="ITEM_ID", nullable=false)
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@Column(name="PATH", length=200)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name="PUBLICO", length=1)
	public Character getPublico() {
		return this.publico;
	}

	public void setPublico(Character publico) {
		this.publico = publico;
	}




}


