package com.iago.springapp.domain.pojo;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NotasId generated by hbm2java
 */
@Embeddable
public class NotasId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private BigDecimal userId;
	private BigDecimal itemId;

	public NotasId() {
	}

	public NotasId(BigDecimal userId, BigDecimal itemId) {
		this.userId = userId;
		this.itemId = itemId;
	}


	@Column(name="USER_ID", nullable=false, precision=22, scale=0)
	public BigDecimal getUserId() {
		return this.userId;
	}

	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

	@Column(name="ITEM_ID", nullable=false, precision=22, scale=0)
	public BigDecimal getItemId() {
		return this.itemId;
	}

	public void setItemId(BigDecimal itemId) {
		this.itemId = itemId;
	}


	public boolean equals(Object other) {
		if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof NotasId) ) return false;
		NotasId castOther = ( NotasId ) other; 

		return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
				&& ( (this.getItemId()==castOther.getItemId()) || ( this.getItemId()!=null && castOther.getItemId()!=null && this.getItemId().equals(castOther.getItemId()) ) );
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
		result = 37 * result + ( getItemId() == null ? 0 : this.getItemId().hashCode() );
		return result;
	}   


}


