package com.iago.springapp.domain.pojo;

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Notas generated by hbm2java
 */
@Entity
@Table(name="NOTAS", schema="IAGO")
public class Notas implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private NotasId id;
	private Items items;
	private BigDecimal nota;

	public Notas() {
	}


	public Notas(NotasId id, Items items) {
		this.id = id;
		this.items = items;
	}
	public Notas(NotasId id, Items items, BigDecimal nota) {
		this.id = id;
		this.items = items;
		this.nota = nota;
	}

	@EmbeddedId

	@AttributeOverrides( {
		@AttributeOverride(name="userId", column=@Column(name="USER_ID", nullable=false, precision=22, scale=0) ), 
		@AttributeOverride(name="itemId", column=@Column(name="ITEM_ID", nullable=false, precision=22, scale=0) ) } )
	public NotasId getId() {
		return this.id;
	}

	public void setId(NotasId id) {
		this.id = id;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="ITEM_ID", nullable=false, insertable=false, updatable=false)
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@Column(name="NOTA", precision=22, scale=0)
	public BigDecimal getNota() {
		return this.nota;
	}

	public void setNota(BigDecimal nota) {
		this.nota = nota;
	}

}


